force_cast: error
force_try: error
force_unwrapping: error
line_length: 200
type_body_length: 250
file_length: 500
type_name:
  min_length: 2
identifier_name:
  min_length: 2
cyclomatic_complexity: 10
included:
  - Sources
  - Demo
  - UnitTests
analyzer_rules:
  - unused_import
  - unused_private_declaration
