version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.4.1"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: xrun -project FinniversKit.xcodeproj -scheme Demo test | xcpretty


        # xcodebuild -project FinniversKit.xcodeproj -scheme "Demo" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.4,name=iPhone X' test | xcpretty

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
